---
title: "Probability"
author: "Math 144"
date: "February 12, 2016"
output: ioslides_presentation
---

## Probability definition
"Proportion of times the outcome would occur if we observed the *random* process an **infinite** number of times"

## Notation
$P(A)$ is the probability of $A$ occurring

## Law of large numbers
As more observations are collected, the proportion $\hat{p}_n$ of occurrences with a particular outcome converges to the probability $p$ of that outcome.

## An example
One step to improving children’s dental care is to understand how often they go to the dentist. A 2005
report from National Center for Health Statistics 1 found the following distribution of times since the last visit:

Length of time | Less than 6 mos | 6 mos - 1 year | 1 year - 2 years | 2 years - 5 years | More than 5 years
---------------|-----------------|----------------|------------------|-------------------|-------------------
Proportion     | 0.57            | 0.18           | 0.08             | 0.03              | ?

* What is the probability that a randomly chosen child has not been to a dentist within the last 6 months?
* What is the probability that a randomly chosen child has been to the dentist within the previous year?
* Find the probability that a randomly chosen child has not gone to the dentist for more than 5 years.

## Disjoint/mutually exclusive

Def: A and B are disjoint if both cannot happen

> - Examples?

> - Addition rule of disjoint outcomes: $P(A \ or \ B) = P(A) + P(B)$

> - Why isn't this always true?

## Examples
> - I roll a fair 6-sided die. What is the probability that I get an even number or a 3?

> - I roll a fair 6-sided die. What is the probability that I get an even number of a multiple of 3?

## General addition rule
$P(A \ or \ B) = P(A) + P(B) - P(A \ and \ B)$

## The "and" vs the "or"
What do we mean in math when we say "or"?


## Assumptions for probability distributions
* List of outcomes disjoint
* Every probability must be between 0 and 1
* The sum of the probabilities must be 1

Why?

## Independence
Suppose we have two independent variables. What does this tell us?

## Handedness

> * Suppose 13% of men and 13% of women are left handed. If a population is 50% male/50% female, can we say that gender and handedness are independent? How can we represent this?
> * What if the population is 40% male / 60% female?
> * What if 13% of men are LH and 14% of women are, with 50% men and 50% women?
> * What if 13% of men are LH and 14% of women are, with 60% men and 40% women?
> * In each situation, how could we find $P(LH \ and \ M)$?
> * We can also represent this with a tree
> * Notice: for the independent situations: $P(LH \ and \ M) = P(LH) * P(M)$

## Test for independence
The last equation can be used as a test:
$P(A \ and \ B) = P(A) * P(B)$ if and only if $A$ and $B$ are independent

## Another example
> * Given that 0.4% of women, 7% of men color blind (CB), and that there are 50% women in the population,
find the proportion of color blind people in the population.

> * Find $P(CB \ and \ M)$ and $P(CB) * P(M)$. What do you notice?

## Using independence
> * Suppose the sex of babies in successive births are independent. Find the probability of all girls in family of
three children. Assume the probability of a girl is $1/2$.
> * Now assume the probability of a girl is 48% (This is the actual figure). Find the probability of all girls in a
family of three.
> * What is the probability of two girls and a boy in a family of three children, if the boy is the youngest? Use $P(G) = 0.48$.
> * What is the probability of two girls and one boy in a family of three children, in any order. Again, use $P(G) = 0.48$.
> * What is the probability of one girls and two boys in a family of three children, in any order. Again, use $P(G) = 0.48$.

## Conditional probability
In our colorblind example, we said that 0.4% of women, 7% of men color blind (CB). We can notate this:

\[P(CB | W) = 0.004\]
and
\[P(CB | M) = 0.07\]

(The "|" is read "given")

This is just restricting the population we're looking at!