---
title: 'Lab 1: Intro to R, Rstudio, and RMarkdown'
author: "Math 145"
date: "September 6, 2017"
output:
  html_document: default
  pdf_document: default
---


Welcome to R! This document is yours to work with and edit!

R is software for doing statistical analysis, and this document is designed to get you started with the programs.

You should have already gotten both R and RStudio installed on your computer. If not - check with your instructor about that. If you have, you should be reading this text in the top-left box on a screen with four boxes in it. In general, this is the box that you'll use to type your results and instructions for the computer to do the analysis.

## RStudio and R Markdown

This document is called an "R Markdown" document. One benefit of using this format is that a single document will contain both your write-up and your analysis. This means that if you need to change a part of either your prose or your analysis, you can change it in this document, and then regenerate your report. To generate a report, you will click the button that says "Knit" right above this box. Try it now! You should see some text in the box below (which we won't worry about for now) and a new screen pops up. This is your generated document.

You can make a new R Markdown document by clicking "file" at the top-left of the screen, selecting new file, then R Markdown. Give it a title and author, and click ok. You'll be given a skeleton of a document. The default is to make an html document (ready to post to the web), but you can change it to a pdf (this requires another download too) or a word document. We'll stick with html output. Click the little gear next to the knit button, and select "output options" to see the choices. Try switching to another output option, and click the knit button. We'll be making our own document, so you can delete everything after the second ---. Those first few lines just tell R how to format the document.

You won't need a whole lot of formatting for our course, but a nice resource is: https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf. For example, if you want to make a bulleted list, you can just use asterisks (or dashes). For example, in this document, we'll see:
* intro to R
* intro to RStudio
* intro to rmarkdown
* intro to mosaic

So, that gives you a rough idea of how R Markdown works. One thing that you will notice is that RStudio doesn't check your spelling as you type. There's a button above this box with "ABC" which starts the spell checker, or you can select it in the "edit" menu, or you can hit F7.

## Introduction to R

R is executed by typing commands for the computer to interpret. While we'll get into some more detailed commands later in the course, let's try to have the computer execute some code.

Above this box there is a button that says "insert." Click the box and select "R." You should see a little grey box show up below where your mouse was when you clicked insert.

Inside this box, we'll give R some commands. If we want to generate some data and view a histogram of it, we can use the following two lines:

x <- rnorm(50)
hist(x)

(We'll be making nicer looking graphs soon!)

Copy those two lines inside the grey box, then hit control (or command) + shift + enter. You should see a plot show up in your window. Now if you click the knit button, you'll see your graph show up as part of your output.

There are lots of options to explore and ways to edit your output to make it look like you want it. For now, this allows you to generate documents which contain your analysis all from within RStudio.

## Introduction to Mosaic

One of the features of R is that it has a huge and active community developing it. The primary way people contribute to R is through "packages." On the right-bottom panel of RStudio, there's a box which has tabs, one of which is "Packages." Click that tab, and you'll see the list of packages which have already been downloaded and installed. We're going to add one more package to that list - `mosaic`.

In the packages tab, click "Install" and type "mosaic." When you click "install," the computer will do some work downloading the package and installing it. You'll only need to do this once - once the package is installed, you have it available to you.

Once a package is installed, you need to "load" it. Scroll down your list of packages until you find the mosaic package, and click the check box to the left of it. This will load the package. RStudio doesn't load all your packages by default - you just load packages as you need them. We'll be using the mosaic package a lot, though!